[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
 repo = 'ryanoasis/nerdtree'
  hook_add = '''
 	nnoremap <silent><C-e> :NERDTreeToggle<CR>
 	let g:NERDTreeDirArrows = 1
 '''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']
hook_add = '''
 	let g:airline_theme = 'wombat'
    let g:airline#extensions#tabline#enabled = 1
    let g:airline_powerline_fonts=1
 	'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

