[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
	nnoremap <silent><C-e> :NERDTreeToggle<CR>
	let g:NERDTreeDirArrows = 1
	'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
	let g:ale_sign_error = ''
	let g:ale_sign_warning = ''
	let g:airline#extensions#ale#open_lnum_symbol = '('
	let g:airline#extensions#ale#close_lnum_symbol = ')'
	let g:ale_echo_msg_format = '[%linter%]%code: %%s'
	highlight link ALEErrorSign Tag
	highlight link ALEWarningSign StorageClass
	nnoremap <silent> <C-k> <Plug>(ale_previous_wrap)
	nnoremap <silent> <C-j> <Plug>(ale_next_wrap)
	'''
	
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes', '/vim-devicons']
hook_add = '''
	let g:airline_powerline_fonts = 1
	let g:airline#extensions#tabline#fnamemod = ':t'
	let g:airline_theme = 'wombat'
	set laststatus=2
	let g:airline#extensions#branch#enabled = 1
	let g:airline#extensions#tabline#enabled = 1
	let g:airline#extensions#wordcount#enabled = 0
	let g:airline#extensions#default#layout = [['a', 'b', 'c'], ['x', 'y', 'z']]
	let g:airline_section_c = '%t'
	let g:airline_section_x = '%{&filetype}'
	let g:airline_section_z = '%3l:%2v %{airline#extensions#ale#get_warning()} %{airline#extensions#ale#get_error()}'
	let g:airline#extensions#ale#error_symbol = ' '
	let g:airline#extensions#ale#warning_symbol = ' '
	let g:airline#extensions#default#section_truncate_width = {}
	let g:airline#extensions#whitespace#enabled = 1
	'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
	nnoremap <silent><C-p> :QuickRun<CR>
	nnoremap <silent><C-c> :!latexmk -c<CR>
	let g:quickrun_config = {}
	let g:quickrun_config['tex'] = {
            \   'command' : 'latexmk', 
            \   'outputter' : 'error',
            \   'outputter/error/error' : 'quickfix',
            \   'args' : '-pv', 
            \   'cmdopt': '-pdfdvi',
            \   'exec': ['%c %a %o %s'],
            \ }
	'''

