[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_source = '''
	colorscheme molokai
	set t_Co=256
''' 

# サイドバー
[[plugins]]
repo = 'preservim/nerdtree'
hook_source = '''
 	map <C-n> :NERDTree<CR>
 	let NERDTreeShowHidden = 1
 	let g:NERDTreeDirArrows = 1
 '''

# airline
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_source = '''
 	let g:airline#extensions#tabline#enabled = 1
 	nmap <C-,> <Plug>AirlineSelectPrevTab
	nmap <C-.> <Plug>AirlineSelectNextTab
 '''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_source = '''
 	let g:airline_theme="molokai"
'''