shell = "bash"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.85
startup_mode = "Maximized"
dynamic_title = true
padding = { x = 4, y = 0 }
option_as_alt = "Both"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 12.0
offset = { x = 0, y = 2 }

[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

[keyboard]
bindings = [
    { key = ".", mods = "Control", action = "ToggleViMode" }
]
