apps:
  pages:
  - number: 1
    items:
    - App Store
    - Safari
    - Mail
    - Contacts
    - Calendar
    - Reminders
    - Notes
    - Messages
    - Maps
    - Find My
    - Photos
    - Preview
    - Music
    - Dictionary
    - System Preferences
    - folder: Other
      pages:
      - number: 1
        items:
        - Shortcuts
        - QuickTime Player
        - TextEdit
        - Grapher
        - Time Machine
        - Font Book
        - Chess
        - Stickies
        - Image Capture
        - VoiceOver Utility
        - AirPort Utility
        - Migration Assistant
        - Terminal
        - Activity Monitor
        - Console
        - Keychain Access
        - System Information
        - Automator
        - Script Editor
        - Disk Utility
        - Digital Color Meter
        - ColorSync Utility
        - Screenshot
        - Bluetooth File Exchange
        - Audio MIDI Setup
    - folder: Default Apps
      pages:
      - number: 1
        items:
        - Stocks
        - Books
        - Voice Memos
        - TV
        - Podcasts
        - FaceTime
        - Photo Booth
        - Siri
        - Home
        - Mission Control
        - Calculator
    - iTerm
    - Clipy
    - DeepL
    - CotEditor
    - Alfred 4
    - Visual Studio Code
    - Rectangle
    - KeyboardCleanTool
    - Dozer
    - Mathpix Snipping Tool
    - Google Drive
    - Google Docs
    - Google Slides
    - Google Sheets
    - Slack
    - zoom.us
widgets:
  pages: []
dock_items:
    - Finder
    - Safari
    - Mail
    - Calendar
    - iTerm
    - CotEditor
    - Visual Studio Code
    - Reminders
    - Slack
    - Music
- ============
desktop: {}
