[tools]
# bat = "latest"
# bun = "latest"
# "ubi:fastfetch-cli/fastfetch" = "latest"
# "npm:@google/gemini-cli" = "latest"
# jq = "latest"
# lazygit = "latest"
# node = "latest"
# uv = "latest"
# vim = "latest"
# ripgrep = "latest"

# LSP
# "npm:bash-language-server" = "latest"
# lua-language-server = "latest"
# "pipx:pyright" = "latest"
# "ubi:tombi-toml/tombi" = "latest"
# "npm:typescript-language-server" = "latest"
# "npm:vim-language-server" = "latest"
# "npm:vscode-langservers-extracted" = "latest"
# "npm:yaml-language-server" = "latest"

# Linter/Formatter
# "ubi:biomejs/biome" = "latest"
# shellcheck = "latest"
# shfmt = "latest"
# stylua = "0.19.0"

[settings]
idiomatic_version_file_enable_tools = []
