[env]
AWS_CONFIG_FILE = "${XDG_CONFIG_HOME}/aws/config"
AWS_SHARED_CREDENTIALS_FILE = "${XDG_CONFIG_HOME}/aws/credentials"
NPM_CONFIG_USERCONFIG = "${XDG_CONFIG_HOME}/npm/npmrc"
PI_CONFIG_DIR = "${XDG_CONFIG_HOME}/pi"
PI_CODING_AGENT_DIR = "${XDG_DATA_HOME}/pi/agent"

[tools]
aws = "latest"
bun = "latest"
fd = "latest"
github-cli = "latest"
tmux = "latest"
lazydocker = "latest"
node = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
uv = "latest"

# LSP
"npm:bash-language-server" = "latest"
"npm:@github/copilot-language-server" = "latest"
lua-language-server = "latest"
tombi = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:yaml-language-server" = "latest"

# Linter/Formatter
"npm:markuplint" = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"

# MacOS
"github:machlit/cutler" = { version = "latest", os = ["macos"] }
colima = { version = "latest", os = ["macos"] }
docker-cli = { version = "latest", os = ["macos"] }
lima = { version = "latest", os = ["macos"] }

[settings.npm]
package_manager = "bun"

