[tools]
jq = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "nightly"
node = "20"
ripgrep = "latest"
rye = "latest"
shfmt = "latest"
stylua = "latest"
zellij = "latest"
# helix = "22.12"

[plugins]
# helix = 'https://github.com/CSergienko/asdf-helix'
