[tools]
bun = "latest"
"ubi:fastfetch-cli/fastfetch" = "latest"
"npm:@google/gemini-cli" = "latest"
go = "latest"
jq = "latest"
tmux = "latest"
lazygit = "latest"
node = "latest"
uv = "latest"
ripgrep = "latest"

# LSP
"npm:bash-language-server" = "latest"
"npm:@github/copilot-language-server" = "1.270.0"
"go:golang.org/x/tools/gopls" = "latest"
lua-language-server = "latest"
"ubi:tombi-toml/tombi" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:yaml-language-server" = "latest"

# Linter/Formatter
"npm:markuplint" = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "0.19.0"
"go:github.com/tursodatabase/turso-cli/cmd/turso" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[settings.npm]
bun = true
