[tools]
neovim = "nightly"
node = "latest"
ripgrep = "latest"
uv = "latest"
zellij = "latest"

# LSP
# "npm:bash-language-server" = "latest"
# "npm:biome" = "latest"
# "npm:json-language-server" = "latest"
# lua-language-server = "latest"
# "npm:pyright" = "latest"
# "npm:yaml-language-server" = "latest"

# optional
# lazygit = "latest"
# rust = "latest"
# jq = "latest"
# shellcheck = "latest"
# shfmt = "latest"
# stylua = "latest"

[settings]
experimental = true
