[tools]
fzf = "0.50"
"asdf:richin13/asdf-neovim" = "nightly"
ripgrep = "latest"
zellij = "latest"

# LSP
# "npm:bash-language-server" = "latest"
# "npm:biome" = "latest"
# "npm:json-language-server" = "latest"
# "ubi:latex-lsp/texlab" = "latest"
# lua-language-server = "latest"
# "ubi:tamasfe/taplo" = "latest"
# "npm:vim-language-server" = "latest"
# "npm:yaml-language-server" = "latest"

# Linter/Formatter
# "npm:markdownlint-cli2" = "latest"
# shellcheck = "latest"
# shfmt = "latest"
# stylua = "0.19.0"

# Other
# ffmpeg = "latest"
# jq = "latest"
# lazygit = "latest"
# node = "latest"
# tree-sitter = "latest"
# uv = "latest"
