[settings]
dotfiles.default_mode = "symlink"
env_shell_expand = true
idiomatic_version_file_enable_tools = []
experimental = true

[dotfiles]
"~/.config/**" = "~/.dotfiles/xdg_config/**"
"~/.bashrc/activate" = { block = 'eval "$(~/.local/bin/mise activate bash)"' }  # For non-login shell
"~/.bash_profile/activate" = { block = 'eval "$(~/.local/bin/mise activate bash)"' }  # For non-login shell

[env]
PS1 = '\[\e[32m\]\u \[\e[$([ $? -ne 0 ] && echo 31 || echo 0)m\]➜ \[\e[34m\]\w \[\e[0m\]\$ '
HISTSIZE = 10000
HISTFILESIZE = 20000

XDG_CONFIG_HOME = "${HOME}/.config"
XDG_DATA_HOME = "${HOME}/.local/share"
XDG_CACHE_HOME = "${HOME}/.cache"
XDG_STATE_HOME = "${HOME}/.local/state"

DOTNET_CLI_HOME = "${XDG_DATA_HOME}/dotnet"
HISTFILE = "${XDG_STATE_HOME}/bash/history"
LESSHISTFILE = "${XDG_STATE_HOME}/less/history"
VIMINIT = 'source ${XDG_CONFIG_HOME}/vim/vimrc'

[shell_alias]
ls = "ls --color=auto"
ll = "ls -la"
dd = "du -sch $(ls -A)"

[hooks]
enter = [
  "shopt -s checkwinsize",
  'mkdir -p "${XDG_STATE_HOME}"/bash'
]

[tools]
jq = "latest"
lazygit = "latest"
ripgrep = "latest"

[bootstrap.user]
login_shell = "/bin/bash"

[bootstrap.packages]
# "brew:mole" = "latest"
# "brew-cask:ghostty" = "latest"  # TODO: fix
"brew-cask:sidequest" = "latest"
"brew-cask:stats" = "latest"
"brew-cask:steam" = "latest"
# "brew-cask:whisky" = "latest"

[bootstrap.macos.dock]
autohide = true
tilesize = 128
orientation = "bottom"

[bootstrap.hooks.post-defaults]
run = "killall Dock || true"
