[tools]
jq = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "nightly"
node = "20"
ripgrep = "latest"
rust = "latest"
rye = "latest"
shfmt = "latest"
stylua = "latest"
zellij = "latest"
