[tools]
# ffmpeg = "latest"
# lazygit = "latest"
# neovim = "latest"
# node = "latest"
# tree-sitter = "latest"
# uv = "latest"
# vim = "latest"
# ripgrep = "latest"
# zellij = "latest"

# LSP
# "npm:bash-language-server" = "latest"
# "ubi:biomejs/biome" = "latest"
# "npm:vscode-langservers-extracted" = "latest"
# "ubi:latex-lsp/texlab" = "latest"
# lua-language-server = "latest"
# "ubi:tamasfe/taplo" = "latest"
# "npm:vim-language-server" = "latest"
# "npm:yaml-language-server" = "latest"

# Linter/Formatter
# "npm:markdownlint-cli2" = "latest"
# shellcheck = "latest"
# shfmt = "latest"
# stylua = "0.19.0"
