" ===== Builtin =====
set encoding=utf-8
set autoread hidden splitright splitbelow clipboard=unnamed
set background=dark cursorline number scrolloff=8 list listchars=tab:>\ ,trail:-,nbsp:+
set completeopt=menuone,noinsert,noselect pumheight=10 shortmess=filnxtToOc wildmenu
set expandtab tabstop=2 shiftwidth=0
set hlsearch incsearch ignorecase smartcase
set runtimepath+=$HOME/.local/share/vim | call mkdir($HOME.'/.local/share/vim', 'p')
set noswapfile viminfo= undofile undodir=~/.cache/vim/undo | call mkdir($HOME.'/.cache/vim/undo', 'p')
inoremap <silent> jk <Esc>
nnoremap <C-l> <CMD>nohlsearch<CR><Esc>
nnoremap <space>d <CMD>vert new<BAR>exec 'read !git show HEAD:#'<BAR>setl bt=nofile ro<BAR>difft<BAR>winc p<BAR>difft<CR>
nnoremap - :let f=expand('%:t')<Bar>e %:h<CR>:call search('^.\{-}\V'.f,'cw')<CR>
    let g:netrw_liststyle = 3 | let g:netrw_winsize = -30 | let g:netrw_banner = 0

" ===== Plugin =====
if empty(glob('~/.local/share/vim/autoload/plug.vim'))
    let plug_url = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    silent execute '!curl -fLo ~/.local/share/vim/autoload/plug.vim --create-dirs '.plug_url
endif
call plug#begin('~/.local/share/vim/plugged')
    Plug 'sainnhe/gruvbox-material'
    Plug 'tpope/vim-commentary'
    Plug 'airblade/vim-gitgutter'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
        nnoremap <space>f <CMD>GFiles<CR>
        nnoremap <space>g <CMD>GFiles?<CR>
        nnoremap <space>/ <CMD>RG<CR>
    Plug 'prabirshrestha/vim-lsp'
        let g:lsp_semantic_enabled = 1
        nnoremap <C-]> <plug>(lsp-definition)
        nnoremap grn <plug>(lsp-rename)
        nnoremap grr <plug>(lsp-references)
        nnoremap K <plug>(lsp-hover)
        nnoremap <space>e <plug>(lsp-document-diagnostics)
    Plug 'mattn/vim-lsp-settings'
        let g:lsp_settings_filetype_python = ['ty']
    Plug 'prabirshrestha/asyncomplete.vim'
    Plug 'prabirshrestha/asyncomplete-lsp.vim'
    Plug 'ggml-org/llama.vim'
call plug#end()
colorscheme gruvbox-material
