" ===== Builtin =====
set encoding=utf-8
set autoread
set background=dark
set clipboard=unnamed
set completeopt=menuone,noinsert,noselect pumheight=10
set cursorline
set expandtab tabstop=2 shiftwidth=0
set hidden
set hlsearch incsearch ignorecase smartcase
set list listchars=tab:>\ ,trail:-,nbsp:+
set number
set runtimepath+=$HOME/.local/share/vim
    call mkdir($HOME.'/.local/share/vim', 'p')
set scrolloff=8
set splitright splitbelow
set shortmess=filnxtToOc
set noswapfile viminfo=
set undofile undodir=$HOME/.cache/vim/undo
    call mkdir($HOME.'/.cache/vim/undo', 'p')

inoremap <silent> jk <Esc>
nnoremap <C-l> <CMD>nohlsearch<CR>
nnoremap <space>d <CMD>vert new<BAR>exec 'read !git show HEAD:#'<BAR>setl bt=nofile ro<BAR>difft<BAR>winc p<BAR>difft<CR>
nnoremap <space>n <Plug>NetrwShrink
    let g:netrw_liststyle = 3 | let g:netrw_winsize = -30 | let g:netrw_banner = 0 | let g:netrw_usetab = 1
aug cmpl | au! | au InsertCharPre * if !pumvisible() | cal feedkeys("\<c-x>\<c-o>", 'n') | en | aug END

" ===== Plugin =====
if empty(glob('~/.local/share/vim/autoload/plug.vim'))
    let plug_url = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    silent execute '!curl -fLo ~/.local/share/vim/autoload/plug.vim --create-dirs '.plug_url
endif
call plug#begin('~/.local/share/vim/plugged')
    Plug 'tpope/vim-commentary'
    Plug 'mhinz/vim-signify'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
        nnoremap <space>f <CMD>GFiles<CR>
        nnoremap <space>g <CMD>GFiles?<CR>
        nnoremap <space>/ <CMD>RG<CR>
    Plug 'prabirshrestha/vim-lsp'
        let g:lsp_semantic_enabled = 1
        let g:lsp_async_completion = 1
        set omnifunc=lsp#complete
        nnoremap <C-]> <plug>(lsp-definition)
        nnoremap <C-W>] <CMD>vertical LspDefinition<CR>
        nnoremap grn <plug>(lsp-rename)
        nnoremap grr <plug>(lsp-references)
        nnoremap K <plug>(lsp-hover)
        nnoremap <space>e <plug>(lsp-document-diagnostics)
    Plug 'mattn/vim-lsp-settings'
        let g:lsp_settings_filetype_python = ['ty']
    Plug 'ggml-org/llama.vim'
call plug#end()
colorscheme habamax
