template = true

[set.menuextra.clock]
FlashDateSeparators = false
Show24Hour = true
ShowAMPM = true
ShowDate = true
ShowDayOfWeek = true
ShowSeconds = true

[set.finder]
AppleShowAllFiles = true
AppleShowAllExtensions = true
ShowPathbar = true
ShowExternalHardDrivesOnDesktop = false
ShowHardDrivesOnDesktop = false
ShowMountedServersOnDesktop = false
SidebarTagsSctionDisclosedState = true
ShowRecentTags = false
FXEnableExtensionChangeWarning = false
FXPreferredViewStyle = "Nlsv"
NewWindowTarget = "PfHm"
NewWindowTargetPath = "file://${HOME}"
FXDefaultSearchScope = "SCcf"
FXCalculateAllSizes = false
_FXCalculateAllSizes = false

[set.AppleMultitouchTrackpad]
FirstClickThreshold = 0
TrackpadThreeFingerDrag = false
Clicking = true
TrackpadTrackingSpeed = 3.0

[set.WindowManager]
EnableStandardClickToShowDesktop = false

[set.dock]
tilesize = 128
autohide = true
static-only = false
show-recents = false
autohide-delay = 0.0
autohide-time-modifier = 0.0
expose-group-apps = false
wvous-bl-corner = 10
wvous-br-corner = 5

[set.controlcenter]
"NSStatusItem VisibleCC Bluetooth" = 1

[set.screencapture]
type = "jpg"

[set.NSGlobalDomain]
KeyRepeat = 1
InitialKeyRepeat = 10
trackpad.scaling = 3.0
mouse.scaling = 3.0
mouse.tapBehavior = 1
AppleInterfaceStyle = "Dark"
"com.apple.trackpad.scaling" = 3.0

[vars]
hostname = "MBA"

[command.hostname]
run = """
scutil --set ComputerName $hostname
scutil --set HostName $hostname
scutil --set LocalHostName $hostname
"""
ensure_first = true
sudo = true

[command.keymap]
run = """
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc": 0x700000039, "HIDKeyboardModifierMappingDst": 0x7000000E0}]}'
"""

[command.dock]
run = """
dock_item() { 
    printf '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>%s</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>', "$1" 
} 
Safari=$(dock_item /System/Cryptexes/App/System/Applications/Safari.app)
Mail=$(dock_item /System/Applications/Mail.app)
Calendar=$(dock_item /System/Applications/Calendar.app)
Ghostty=$(dock_item /Applications/Ghostty.app)
defaults delete com.apple.dock persistent-apps
defaults write com.apple.dock persistent-apps -array "$Safari" "$Mail" "$Calendar" "$Ghostty"
Killall Dock
"""

[command.other]
run = """
defaults write com.apple.TextEdit RichText -bool false
defaults -currentHost write com.apple.controlcenter Bluetooth -int 2
"""

[command.thirdparty]
run = """
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
"""

[brew]
formulae = [
    "mole",
]
casks = [
    "ghostty",
    "stats",
]
no_deps = true
