#!/bin/bash

# ===== Settings =====
HISTSIZE=1000
HISTFILESIZE=200000
export PS1='\u@\h \W \$ '
shopt -s checkwinsize

# ===== XGD Based Dirs =====
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

mkdir -p "${XDG_STATE_HOME}"/bash
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export HISTFILE="$XDG_STATE_HOME"/bash/history
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export LESSHISTFILE="$XDG_STATE_HOME"/less/history
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo
export SCREENRC="$XDG_CONFIG_HOME"/screen/screenrc
export SCREENDIR=/tmp/screen-$USER

# ===== Aliases =====
alias ls='ls --color=auto'
alias ll='ls -la'
alias dd='du -sch $(ls -A)'

# ===== Plugins =====
eval "$(~/.local/bin/mise activate bash)"
if [ -d /opt/homebrew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
