" >>> `curl -s https://raw.githubusercontent.com/nomutin/dotfiles/master/config/vimrc -o ~/.vimrc`

" ===== Builtin =====
set encoding=utf-8
set autoread hidden
set background=dark
set clipboard=unnamed
set completeopt=menuone,noinsert,noselect pumheight=10 shortmess+=c
set cursorline ruler
set expandtab tabstop=4 shiftwidth=4
set hlsearch incsearch ignorecase smartcase
set list listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+ nowrap
set regexpengine=2
set splitright splitbelow
set scrolloff=8
set noswapfile viminfo= undofile undodir=~/.vim/undo | call mkdir($HOME.'/.vim/undo', 'p')
set wildmenu
let &t_SI = "\e[5 q" | let &t_SR = "\e[4 q" | let &t_EI = "\e[2 q" 

inoremap <silent> jk <Esc>
nnoremap <C-l> <CMD>nohlsearch<CR><Esc>
nnoremap <space>d <CMD>vert new<BAR>exec 'read !git show HEAD:#'<BAR>setl bt=nofile ro<BAR>difft<BAR>winc p<BAR>difft<CR>
nnoremap <silent> <space>n <CMD>Lex<CR>
    let g:netrw_banner = 0 | let g:netrw_liststyle = 3 | let g:netrw_altv = 1 | let g:netrw_winsize = 30

" ===== Plugin =====
if empty(glob('~/.vim/plugged'))
    let plug_url = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    silent execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs '.plug_url
endif

call plug#begin('~/.vim/plugged')
    Plug 'sainnhe/gruvbox-material'
    Plug 'tpope/vim-commentary'
    Plug 'preservim/nerdtree'
    Plug 'Xuyuanp/nerdtree-git-plugin'
        nnoremap <space>n <CMD>NERDTreeToggle<CR>
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
        let $FZF_DEFAULT_COMMAND = 'rg --files --hidden --follow --glob "!.git/*"'
        nnoremap <space>f <CMD>Files<CR>
        nnoremap <space>/ <CMD>Rg<CR>
    Plug 'prabirshrestha/vim-lsp'
    Plug 'mattn/vim-lsp-settings'
        let g:lsp_diagnostics_virtual_text_enabled = 0
        let g:lsp_async_completion = 1
        let g:lsp_semantic_enabled = 1
        function! LSPSetup() abort
            setlocal signcolumn=yes
            setlocal omnifunc=lsp#complete
            nnoremap <C-]> <plug>(lsp-definition)
            nnoremap <C-W>] <CMD>vertical LspDefinition<CR>
            nnoremap grn <plug>(lsp-rename)
            nnoremap grr <plug>(lsp-references)
            nnoremap K <plug>(lsp-hover)
            nnoremap <space>e <plug>(lsp-document-diagnostics)
            aug cmpl | au! | au InsertCharPre <buffer> if !pumvisible() | cal feedkeys("\<c-x>\<c-o>", 'n') | en | aug END
        endfunction
        aug lsp_install | au! | au User lsp_buffer_enabled cal LSPSetup() | aug END
    Plug 'github/copilot.vim'
call plug#end()
colorscheme gruvbox-material
