# zellij-like keybindings
set -g prefix C-g
unbind C-b

set -s escape-time 1000 
set -g repeat-time 1000

bind-key p switch-client -T pane-mode

bind-key -T pane-mode -r h select-pane -L
bind-key -T pane-mode -r j select-pane -D
bind-key -T pane-mode -r k select-pane -U
bind-key -T pane-mode -r l select-pane -R
bind-key -T pane-mode n split-window -h
bind-key -T pane-mode x split-window -v

bind-key r switch-client -T resize-mode

bind-key -T resize-mode -r h resize-pane -L 5
bind-key -T resize-mode -r j resize-pane -D 5
bind-key -T resize-mode -r k resize-pane -U 5
bind-key -T resize-mode -r l resize-pane -R 5

set -g status-style "bg=#{?#{==:#{client_key_table},pane-mode},red,#{?#{==:#{client_key_table},resize-mode},blue,black}},fg=white"

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
