name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-15, macos-14, ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: bash scripts/install.sh
      - name: Run Health Check
        run: bash scripts/healthcheck.sh
