name: macOS

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Install
        run: bash install.sh
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify ll command
        run: bash -lc 'source ~/.bashrc && ll >/dev/null'
      - name: Verify jq command
        run: bash -lc 'source ~/.bashrc && jq --version >/dev/null'
