name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    name: Lint Shell Scripts and Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup shfmt
        uses: mfinelli/setup-shfmt@v2

      - name: Run shfmt
        run: |
          # shellcheck disable=SC2046
          shfmt -i 2 -ci -d $(shfmt -f . | grep -v '\.zsh$')

      # - name: Run ShellCheck
      #   uses: ludeeus/action-shellcheck@master

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash

      # - uses: JohnnyMorganz/stylua-action@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     version: latest
      #     args: --check .

      - uses: ludvighz/vint-action@v1
        with:
          path: xgd_config/vim/vimrc
