name: Lint Shell

on:
  pull_request:
    branches:
      - master
    paths:
      - "**/*.sh"

jobs:
  linting:
    name: Lint Shell Scripts and Workflows
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@5ebd09ddbe2ebb471646ce234c6c8dd18663ca7c # v1.30.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          pattern: "*.sh"
          exclude: "./.git/*"
