name: Lint Lua

on:
  pull_request:
    branches:
      - master
    paths:
      - "**/*.lua"

jobs:
  linting:
    name: Lint Lua Files
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Install luacheck
        run: sudo apt-get update && sudo apt-get install -y luacheck
      - name: Run luacheck
        run: luacheck .config/
