name: Lint Vimscript

on:
  pull_request:
    branches:
      - master
    paths:
      - "**/vimrc"

jobs:
  linting:
    name: Lint vimscript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Run Vint
        uses: ludvighz/vint-action@31fa19d060969bb48fcfd9044773d665bf03e8c3 # v1
        with:
          path: .config/vim/vimrc
