name: shellcheck

on:
  push:
    branches:
      - master

jobs:
  test:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: shellcheck
        run: make shellcheck
