[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"
env_shell_expand = true
idiomatic_version_file_enable_tools = []
experimental = true

[dotfiles]
"~/.config/**" = {}
"~/.bashrc/activate" = { block = 'eval "$(~/.local/bin/mise activate bash)"' }       # non-login shell
"~/.bash_profile/activate" = { block = 'eval "$(~/.local/bin/mise activate bash)"' } # login shell

[env]
PS1 = '\[\e[32m\]\u \[\e[$([ $? -ne 0 ] && echo 31 || echo 0)m\]➜ \[\e[34m\]\w \[\e[0m\]\$ '
HISTSIZE = 10000
HISTFILESIZE = 20000
XDG_CONFIG_HOME = "${HOME}/.config"
XDG_DATA_HOME = "${HOME}/.local/share"
XDG_CACHE_HOME = "${HOME}/.cache"
XDG_STATE_HOME = "${HOME}/.local/state"

AWS_CONFIG_FILE = "${XDG_CONFIG_HOME}/aws/config"
AWS_SHARED_CREDENTIALS_FILE = "${XDG_CONFIG_HOME}/aws/credentials"
DOCKER_CONFIG = "${XDG_CONFIG_HOME}/docker"
DOTNET_CLI_HOME = "${XDG_DATA_HOME}/dotnet"
HISTFILE = "${XDG_STATE_HOME}/bash/history"
NPM_CONFIG_USERCONFIG = "${XDG_CONFIG_HOME}/npm/npmrc"
LESSHISTFILE = "${XDG_STATE_HOME}/less/history"
PI_CONFIG_DIR = ".config/omp"
VIMINIT = 'source ${XDG_CONFIG_HOME}/vim/vimrc'

[shell_alias]
ls = "ls --color=auto"
ll = "ls -la"
dd = "du -sch $(ls -A)"

[hooks]
enter = ["shopt -s checkwinsize", 'mkdir -p "${XDG_STATE_HOME}"/bash']

[tools]
aws = "latest"
"npm:bash-language-server" = { version = "latest", depends = ["bun"] }
bun = "latest"
github-cli = "latest"
jq = "latest"
"github:atusy/kakehashi" = "latest"
lazydocker = "latest"
lazygit = "latest"
shellcheck = "latest"
shfmt = "latest"
tmux = "latest"
tombi = "latest"
ripgrep = "latest"
uv = "latest"
"npm:vscode-langservers-extracted" = { version = "latest", depends = ["bun"] }
oh-my-pi = { version = "latest", rename_exe = "omp", postinstall = 'mkdir -p "${XDG_CONFIG_HOME}/omp/agent" "${XDG_DATA_HOME}/omp" "${XDG_STATE_HOME}/omp" "${XDG_CACHE_HOME}/omp"' }
"npm:yaml-language-server" = { version = "latest", depends = ["bun"] }

[bootstrap.user]
login_shell = "/bin/bash"
